<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://www.maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.waf</groupId>
        <artifactId>dynamicWAF</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>dynamicWAF-model</artifactId>

    <dependencies>
        <dependency>
            <groupId>org.kie</groupId>
            <artifactId>kie-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.46</version>

        </dependency>
    </dependencies>



</project>