package rules;

import com.waf.dynamicWAF.model.ThreatAlert;
import com.waf.dynamicWAF.model.IpBan;

// Iako smo stavili anotacije u Javi, dobra je praksa (i najsigurnije za odbranu)
// da i u .drl fajlu eksplicitno naglasimo Drools-u da je ovo događaj.
declare ThreatAlert
    @role( event )
    @timestamp( executionTime )
end

rule "Detekcija Brute Force napada preko CEP-a"
when
    // 1. Vežemo se za bilo koji ThreatAlert kako bismo izvukli IP adresu ($ip)
    $alert : ThreatAlert($ip : sourceIp)

    // 2. CEP LOGIKA: Koristimo accumulate da prebrojimo događaje u vremenskom prozoru
    Number(intValue >= 5) from accumulate(
        $t : ThreatAlert(sourceIp == $ip) over window:time( 1m ),
        count($t)
    )

    // 3. Da ne bismo u nedogled okidali pravilo za isti IP,
    // proveravamo da taj IP već nije banovan.
    not IpBan(ipAddress == $ip)
then
    System.out.println("CEP ALARM: Detektovan napad sa IP adrese " + $ip + "! Više od 5 pretnji u minutu.");

    // Akcija: Ubacujemo novu činjenicu da je IP adresa banovana
    insert(new IpBan($ip, "Brute Force detektovan kroz CEP"));
end

// --- NOVO: UPIT ZA DOHVATANJE PODATAKA ---
// Ovaj upit pronalazi sve objekte tipa IpBan koji se trenutno nalaze u radnoj memoriji
query "pribaviSveBanovaneIpAdrese"
    $ban : IpBan()
end